// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_top10_proceduced : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_top10_proceduced));
        
        string IMigrationMetadata.Id
        {
            get { return "201908101834192_add_top10_proceduced"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
