// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addstoredproceducegetrevenuebymoth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addstoredproceducegetrevenuebymoth));
        
        string IMigrationMetadata.Id
        {
            get { return "201908170802236_add-stored-proceduce-get-revenue-by-moth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
